# ===== Base de datos (VM Oracle) =====
spring.datasource.url=${DB_URL:jdbc:postgresql://IP_DE_TU_VM:5432/techmind}
spring.datasource.username=${DB_USERNAME:techmind}
spring.datasource.password=${DB_PASSWORD:techmind}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===== Servidor =====
server.port=8080

# ===== Logging =====
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security=DEBUG